services:
  go-gateway:
    build:
      context: ../..
      dockerfile: _example/Dockerfile.gateway
    ports:
      - "9000:9000"
    volumes:
      - ./gateway.docker.yaml:/app/gateway.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
