services:
  go-gateway:
    build:
      context: ../..
      dockerfile: _example/Dockerfile.gateway
    ports:
      - "9000:9000"
    volumes:
      - ./gateway.docker.yaml:/app/gateway.yaml
      - ./customers:/app/customers
      - ./accounts:/app/accounts
      - ./transactions:/app/transactions
    environment:
      - PORT=9000
